# .rubocop.yml

# ▼ プラグイン（Gemfileに入れている前提）
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable            # 新しいCopを自動有効化
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'Gemfile'

# 改行コードはLFを強制（CRLF混入の検知）
Layout/EndOfLine:
  EnforcedStyle: lf

# 1行の長さ
Layout/LineLength:
  Max: 130
  Exclude:
    - 'Rakefile'
    - 'spec/**/*'            # specは長くなりがちなので除外

# RSpecはブロック長の制限を外す
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 8

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 30

Metrics/BlockNesting:
  Max: 5

Metrics/ClassLength:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ClassAndModuleChildren:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1
