default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_46286_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_46286_test
  # RSpec実行時の `Mysql2::Error: This connection is in use by` エラーを回避するため、
  # テスト環境では非同期クエリを無効にする
  async: false

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>